# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: greekadonis
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: challenge-server
service: challenge-server # NOTE: update this with your service name



provider:
  name: aws
  runtime: python3.10
  lambdaHashingVersion: 20201221
  region: ap-southeast-2

functions:
  server:
    handler: server.lambda_handler

plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: false